### ISSUE TITLE
Has ecs.defineComponent() been changed to ecs.registerComponent()?

### ISSUE THREAD

**Issue by llharry** [EnderShadow8/wolf-ecs#12]
Typescript is giving me `Property 'defineComponent' does not exist on type 'ECS'.`, but it seems to be working fine with registerComponent, so just checking that's how it's meant to work!

**Comment by EnderShadow8** [comment]
That shouldn't happen. What version are you using?

`defineComponent` creates a component storage under the hood, but if you have your own custom storage then you would `registerComponent` it.
