### ISSUE TITLE
example in readme does not compile

### ISSUE THREAD

**Issue by mikecann** [EnderShadow8/wolf-ecs#14]
[in the Queries section in your readme](https://github.com/EnderShadow8/wolf-ecs#queries) you mention:

> To define a query, use ecs.createQuery:
> // Matches entities which have both component1 and component2
> const query = ecs.createQuery(component1, component2)

This however doesnt compile, instead you have to use `all()` to make that work:

![image](https://user-images.githubusercontent.com/215033/190075247-947b2d83-bb82-4075-a82f-57abdb19765f.png)

**Comment by EnderShadow8** [comment]
Sorry about the inconvenience, but I don't believe you should use this for anything substantial.

I originally made this project to demonstrate the speed limit for JS ECS, however, in the process of making everything fast, I slowly sacrificed usability to the point where this serves only as a demonstration of speed in benchmarks, and nothing more. I'm hoping that ideas I've developed will make their way into more mature projects such as https://github.com/NateTheGreatt/bitECS

In the meantime, I'll update the readme to include this information, as I never got round to doing it and forgot.

Thanks for checking it out anyway! 😄
