### ISSUE TITLE
defineQuery is missing? need to update readme

### ISSUE THREAD

**Issue by lslzl3000** [EnderShadow8/wolf-ecs#8]
ecs.defineQuery is missing in new version, please update readme and show some new demos of how to use query()/createQuery() with all/not/any, maybe more about match() as well

**Comment by EnderShadow8** [comment]
Nice catch, I've fixed it. It's meant to be `createQuery`, I think I was writing a BitECS compat layer when I wrote that.

`match()` was meant to be an internal function, sorry if that caused confusion.
